import pygame

FIELD_MATRIX_ROWS = 25
FIELD_MATRIX_COLS = 50

NUM_OF_OBSTACLES = 20
NO_OBSTACLE = 'EMPTY'

MINE = 'MINE'
MINE_WIDTH = 3

BUSH = 'BUSH'
BUSH_WIDTH = 3
BUSH_HEIGHT = 2

FLAG = 'FLAG'
FLAG_WIDTH = 4
FLAG_HEIGHT = 3
FLAG_LOCATION = (21, 46)

SOLDIER_WIDTH = 2
SOLDIER_HEIGHT = 4

STEP = 1

UP = 'UP'
DOWN = 'DOWN'
LEFT = 'LEFT'
RIGHT = 'RIGHT'


# SCREEN
WINDOW_WIDTH, WINDOW_HEIGHT = 1000, 500
WINDOW = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))
INDEX_WIDTH, INDEX_HEIGHT = 20, 20

pygame.display.set_caption("The Flag")

PLAYER_WIDTH, PLAYER_HEIGHT = INDEX_WIDTH*2, INDEX_HEIGHT*4
HEAD_WIDTH, HEAD_HEIGHT = INDEX_WIDTH*3, INDEX_HEIGHT*2
PORTAL_WIDTH, PORTAL_HEIGHT = INDEX_WIDTH*3, INDEX_HEIGHT*1

BLACK = (0, 0, 0)
LIGHT_GREEN = (16, 222, 19)
BORDER = pygame.Rect(WINDOW / 2, 0, 1, WINDOW_HEIGHT)